/**
 * Phase 15 — deterministic stand-ins for the stepper's compute passes, for use
 * with mock-gpu.ts.
 *
 * These are NOT ports of the WGSL. They exist so that the stepper's CPU-side
 * orchestration (readbacks, population restructuring, re-upload) can run
 * against a device whose buffers evolve in a known, scriptable way:
 *
 *   - mechanics / charge / health passes apply simple, deterministic updates
 *     that make every particle's GPU state unique and time-varying, so a
 *     round trip that loses, freezes, shifts or resets state is detectable;
 *   - communication events, local success and health drops are driven by a
 *     script keyed by ParticleID and timestep, so scenarios can force deaths,
 *     births and message traffic at exact steps;
 *   - the two compaction passes implement the SAME predicates as the WGSL
 *     (SHADER_DEATH_COMPACTION / SHADER_REPRODUCTION_COMPACTION), because the
 *     stepper's event handling consumes their output directly.
 */
import type { KernelContext, KernelEmulator, MockBuffer } from './mock-gpu';

const UINT32_MAX = 0xffffffff;

/** Same FNV-1a as MfmWebGPUStepper.hashParticleId. */
export function fnv1a(id: string): number {
  let hash = 2166136261 >>> 0;
  for (let i = 0; i < id.length; i++) {
    hash ^= id.charCodeAt(i);
    hash = Math.imul(hash, 16777619) >>> 0;
  }
  return hash >>> 0;
}

export interface KernelScript {
  /** Health removed from an internal particle by the health pass at GPU timestep `timestep`. */
  healthDrop?(id: string, timestep: number): number;
  /** Whether the local-success pass marks this particle successful. */
  success?(id: string, timestep: number): boolean;
  /** Communication events (sender -> target) produced at GPU timestep `timestep`. */
  events?(timestep: number, liveIds: string[]): Array<[string, string]>;
}

const u32 = (b: MockBuffer): Uint32Array => new Uint32Array(b.data);
const f32 = (b: MockBuffer): Float32Array => new Float32Array(b.data);

function computeQOut(a: number, theta: number): number {
  const amplification = Math.fround(a);
  const th = Math.fround(Math.min(Math.max(Math.floor(theta), 0), UINT32_MAX));
  const produced = Math.floor(Math.fround(amplification * th) + 0.5);
  return Math.min(Math.max(produced, 0), UINT32_MAX) >>> 0;
}

export function createKernelEmulator(script: KernelScript, knownIds: Iterable<string>): KernelEmulator {
  const idByHash = new Map<number, string>();
  for (const id of knownIds) idByHash.set(fnv1a(id), id);
  // Offspring ids are generated by the stepper as `offspring-<timestep>-<n>`.
  for (let t = 0; t < 400; t++) {
    for (let n = 0; n < 64; n++) {
      const id = `offspring-${t}-${n}`;
      idByHash.set(fnv1a(id), id);
    }
  }

  const liveIds = (context: KernelContext, count: number): string[] => {
    const hashes = u32(context.device.findBuffer('mfm-id-hash'));
    const ids: string[] = [];
    for (let i = 0; i < count; i++) ids.push(idByHash.get(hashes[i]) ?? `hash:${hashes[i]}`);
    return ids;
  };

  return (context: KernelContext): void => {
    const { bindings, label } = context;
    const paramsBuffer = bindings.get(0);
    const params = paramsBuffer ? new DataView(paramsBuffer.data, context.paramsOffset, 112) : null;
    const activeCount = params ? params.getUint32(0, true) : 0;
    const timestep = params ? params.getUint32(16, true) : 0;

    // Unlabelled 4-binding pipeline == MetricsReducer (webgpu-core), which creates its pipeline without a label.
    if (label === '' && bindings.size === 4) {
      const health = bindings.get(0)!;
      const charge = bindings.get(1)!;
      const result = bindings.get(2)!;
      const count = u32(bindings.get(3)!)[0];
      const healthView = u32(health);
      const chargeView = u32(charge);
      const out = u32(result);
      for (let i = 0; i < count; i++) {
        out[i * 2] = healthView[i];
        out[i * 2 + 1] = chargeView[i];
      }
      return;
    }

    // Phase 20: every WGSL kernel starts with `if (params.halted != 0u) { return; }` (Params offset 108).
    if (label !== '' && params && params.getUint32(108, true) !== 0) return;

    switch (label) {
      case 'mfm-halt-update': {
        // Mirrors SHADER_HALT_UPDATE (the guard above already handled params.halted).
        const deathCount = u32(bindings.get(1)!);
        const candidateCount = u32(bindings.get(2)!);
        const halt = u32(bindings.get(3)!);
        if (deathCount[0] > 0 || candidateCount[0] > 0) halt[0] = 1;
        return;
      }

      case 'mfm-grid-clear':
      case 'mfm-grid-build':
      case 'mfm-pressure':
      case 'mfm-communication-select':
      case 'mfm-force':
      case 'mfm-force-all-pairs':
      // Phase 18: the cell-sorted force path. The mock only checks dispatch order, bindings and buffer lifetimes; force values are not emulated.
      case 'mfm-sort-count':
      case 'mfm-sort-scan':
      case 'mfm-sort-scatter':
        return;

      case 'mfm-charge-process': {
        const chargeIn = u32(bindings.get(1)!);
        const incoming = u32(bindings.get(2)!);
        const role = u32(bindings.get(3)!);
        const theta = u32(bindings.get(4)!);
        const a = f32(bindings.get(5)!);
        const residual = u32(bindings.get(6)!);
        const active = u32(bindings.get(7)!);
        const qOut = u32(bindings.get(8)!);
        for (let i = 0; i < activeCount; i++) {
          residual[i] = (chargeIn[i] + incoming[i]) >>> 0;
          active[i] = role[i] === 0 && residual[i] >= theta[i] ? 1 : 0;
          qOut[i] = computeQOut(a[i], theta[i]);
        }
        return;
      }

      case 'mfm-charge-finalize': {
        const residual = u32(bindings.get(1)!);
        const chargeOut = u32(bindings.get(2)!);
        const qmax = params!.getUint32(24, true);
        const deltaQ = params!.getUint32(32, true);
        for (let i = 0; i < activeCount; i++) {
          const r = residual[i];
          const postDecay = r > 0 ? r - Math.min(r, deltaQ) : 0;
          chargeOut[i] = Math.min(qmax, postDecay) >>> 0;
        }
        return;
      }

      case 'mfm-communication-transmit': {
        if (params!.getUint32(12, true) !== 0) return; // rank 0 carries the whole scripted event list
        const qOut = u32(bindings.get(1)!);
        const incomingWrite = u32(bindings.get(3)!);
        const eventCount = u32(bindings.get(4)!);
        const senders = u32(bindings.get(5)!);
        const targets = u32(bindings.get(6)!);
        const ids = liveIds(context, activeCount);
        for (const [senderId, targetId] of script.events?.(timestep, ids) ?? []) {
          const senderSlot = ids.indexOf(senderId);
          const targetSlot = ids.indexOf(targetId);
          if (senderSlot < 0 || targetSlot < 0) continue;
          const index = eventCount[0]++;
          senders[index] = senderSlot;
          targets[index] = targetSlot;
          incomingWrite[targetSlot] = (incomingWrite[targetSlot] + qOut[senderSlot]) >>> 0;
        }
        return;
      }

      case 'mfm-local-success': {
        const successful = u32(bindings.get(4)!);
        const role = u32(context.device.findBuffer('mfm-role'));
        const ids = liveIds(context, activeCount);
        for (let i = 0; i < activeCount; i++) {
          successful[i] = role[i] === 0 && script.success?.(ids[i], timestep) ? 1 : 0;
        }
        return;
      }

      case 'mfm-health-update': {
        const healthIn = f32(bindings.get(1)!);
        const role = u32(bindings.get(2)!);
        const hmax = f32(bindings.get(3)!);
        const successful = u32(bindings.get(4)!);
        const healthOut = f32(bindings.get(6)!);
        const ids = liveIds(context, activeCount);
        for (let i = 0; i < activeCount; i++) {
          if (role[i] !== 0) {
            healthOut[i] = healthIn[i];
            continue;
          }
          const next = healthIn[i] + (successful[i] !== 0 ? 1 : 0) - (script.healthDrop?.(ids[i], timestep) ?? 0);
          healthOut[i] = Math.min(Math.max(next, 0), hmax[i]);
        }
        return;
      }

      case 'mfm-mechanics': {
        const positionsIn = f32(bindings.get(1)!);
        const velocitiesIn = f32(bindings.get(2)!);
        const role = u32(bindings.get(4)!);
        const positionsOut = f32(bindings.get(7)!);
        const velocitiesOut = f32(bindings.get(8)!);
        const lx = params!.getFloat32(44, true);
        const ly = params!.getFloat32(48, true);
        const wrap = (value: number, length: number): number => ((value % length) + length) % length;
        for (let i = 0; i < activeCount; i++) {
          if (role[i] !== 0) {
            positionsOut[i * 2] = positionsIn[i * 2];
            positionsOut[i * 2 + 1] = positionsIn[i * 2 + 1];
            velocitiesOut[i * 2] = 0;
            velocitiesOut[i * 2 + 1] = 0;
            continue;
          }
          const vx = velocitiesIn[i * 2] + 0.01;
          const vy = velocitiesIn[i * 2 + 1] + 0.02;
          velocitiesOut[i * 2] = vx;
          velocitiesOut[i * 2 + 1] = vy;
          positionsOut[i * 2] = wrap(positionsIn[i * 2] + 0.25 + vx, lx);
          positionsOut[i * 2 + 1] = wrap(positionsIn[i * 2 + 1] + 0.125 + vy, ly);
        }
        return;
      }

      case 'mfm-death-compaction': {
        // Mirrors SHADER_DEATH_COMPACTION: role internal && healthOut <= 0.
        const healthOut = f32(bindings.get(1)!);
        const role = u32(bindings.get(2)!);
        const deathCount = u32(bindings.get(3)!);
        const deathSlots = u32(bindings.get(4)!);
        let count = 0;
        for (let i = 0; i < activeCount; i++) {
          if (role[i] === 0 && healthOut[i] <= 0) deathSlots[count++] = i;
        }
        deathCount[0] = count;
        return;
      }

      case 'mfm-reproduction-compaction': {
        // Mirrors SHADER_REPRODUCTION_COMPACTION.
        const positions = f32(bindings.get(1)!);
        const velocities = f32(bindings.get(2)!);
        const healthIn = f32(bindings.get(3)!);
        const healthOut = f32(bindings.get(4)!);
        const role = u32(bindings.get(5)!);
        const mateThreshold = f32(bindings.get(6)!);
        const successful = u32(bindings.get(7)!);
        const candidateCount = u32(bindings.get(8)!);
        const geometry = f32(bindings.get(9)!);
        const candidateSlots = u32(bindings.get(10)!);
        let count = 0;
        for (let i = 0; i < activeCount; i++) {
          const eligible =
            role[i] === 0 && healthIn[i] >= mateThreshold[i] && successful[i] !== 0 && healthOut[i] > 0;
          if (!eligible) continue;
          candidateSlots[count] = i;
          geometry[count * 4] = positions[i * 2];
          geometry[count * 4 + 1] = positions[i * 2 + 1];
          geometry[count * 4 + 2] = velocities[i * 2];
          geometry[count * 4 + 3] = velocities[i * 2 + 1];
          count++;
        }
        candidateCount[0] = count;
        return;
      }

      default:
        throw new Error(`kernel emulator: no emulation for pipeline "${label}" (${bindings.size} bindings)`);
    }
  };
}
