export interface MFMConfigData {
    readonly version: string;
    readonly Lx: number;
    readonly Ly: number;
    readonly Nmax: number;
    readonly dt: number;
    readonly seed: number;
    readonly Qmax: number;
    readonly R_s_min: number;
    readonly R_s_max: number;
    readonly boundary: 'periodic';
    readonly Q_in_max: number;
    readonly delta_q: number;
    readonly beta: number;
    readonly lambda: number;
    readonly P_min: number;
    readonly P_max: number;
    readonly pressure_gamma: number;
    readonly R_mate: number;
    readonly H_mate: number;
    readonly H_birth: number;
    readonly mate_radius_percent: number;
    readonly mate_health_percent: number;
    readonly birth_health_percent: number;
    readonly mating_probability: number;
    readonly communication_alpha: number;
    readonly Hmax: number;
    readonly theta_q: number;
    readonly A: number;
    readonly K: number;
    readonly Rc: number;
    readonly m: number;
    readonly gamma: number;
    readonly Rs: number;
    readonly omega_R: number;
    readonly omega_A: number;
    readonly omega_v: number;
    readonly genome_variation: number;
}
export declare class MFMConfig implements MFMConfigData {
    readonly version: string;
    readonly Lx: number;
    readonly Ly: number;
    readonly Nmax: number;
    readonly dt: number;
    readonly seed: number;
    readonly Qmax: number;
    readonly R_s_min: number;
    readonly R_s_max: number;
    readonly boundary: 'periodic';
    readonly Q_in_max: number;
    readonly delta_q: number;
    readonly beta: number;
    readonly lambda: number;
    readonly P_min: number;
    readonly P_max: number;
    readonly pressure_gamma: number;
    readonly R_mate: number;
    readonly H_mate: number;
    readonly H_birth: number;
    readonly mate_radius_percent: number;
    readonly mate_health_percent: number;
    readonly birth_health_percent: number;
    readonly mating_probability: number;
    readonly communication_alpha: number;
    readonly Hmax: number;
    readonly theta_q: number;
    readonly A: number;
    readonly K: number;
    readonly Rc: number;
    readonly m: number;
    readonly gamma: number;
    readonly Rs: number;
    readonly omega_R: number;
    readonly omega_A: number;
    readonly omega_v: number;
    readonly genome_variation: number;
    constructor(data?: Partial<MFMConfigData>);
    static validate(obj: unknown): obj is MFMConfigData;
    validate(): void;
    toJSON(): MFMConfigData;
    static fromJSON(obj: unknown): MFMConfig;
}
